# nginx.conf.tpl -- Live CSS Editor
# THIS IS A TEMPLATE.  Do not edit conf/nginx.conf directly; it is generated
# by server/setup.sh with machine-specific paths substituted.
#
# Placeholders (replaced by setup.sh via sed):
#   @@PROJECT_DIR@@  -- absolute path to the live-css project root
#   @@SERVER_DIR@@   -- absolute path to the server/ sub-directory

# No "user" directive -- brew nginx runs as the installing user, no root needed.
worker_processes auto;

# Keep per-worker FD limit above worker_connections to suppress nginx warning.
worker_rlimit_nofile 1024;

pid  @@SERVER_DIR@@/run/nginx.pid;

error_log  @@SERVER_DIR@@/logs/nginx-error.log  warn;

events {
    worker_connections 1024;
}

http {
    include      /usr/local/etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log  @@SERVER_DIR@@/logs/nginx-access.log;

    sendfile        on;
    tcp_nopush      on;
    keepalive_timeout 65;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript
               text/xml application/xml application/xml+rss text/javascript;

    # ── Auth / billing reverse proxy (port 8445) ──────────────────────────────
    include @@SERVER_DIR@@/conf/proxy-auth.conf;

    # ── HTTP test proxy (port 8088) -- plain HTTP, no TLS ─────────────────────
    # Allows quick curl / browser testing of billing proxy routes without needing
    # the mkcert CA installed.  Only binds to loopback; never exposed externally.
    # Port 8080 is already used by the PHP dev server on this machine.
    server {
        listen  127.0.0.1:8088;
        server_name localhost;

        resolver 8.8.8.8 8.8.4.4 valid=300s ipv6=off;
        resolver_timeout 5s;

        proxy_ssl_protocols     TLSv1.2 TLSv1.3;
        proxy_ssl_session_reuse on;
        proxy_ssl_verify        on;
        proxy_ssl_trusted_certificate /etc/ssl/cert.pem;

        proxy_buffer_size          16k;
        proxy_buffers              8 128k;
        proxy_busy_buffers_size    256k;
        proxy_connect_timeout  15s;
        proxy_send_timeout     60s;
        proxy_read_timeout     60s;
        proxy_no_cache      1;
        proxy_cache_bypass  1;
        proxy_set_header  Connection        "";
        proxy_http_version 1.1;
        proxy_set_header  X-Forwarded-For  "";
        proxy_set_header  X-Real-IP        "";
        proxy_set_header  X-Forwarded-Proto https;
        proxy_pass_header Set-Cookie;

        proxy_cookie_domain platform.claude.com   localhost;
        proxy_cookie_domain platform.openai.com   localhost;
        proxy_cookie_domain console.anthropic.com localhost;
        proxy_cookie_domain anthropic.com         localhost;
        proxy_cookie_domain openai.com            localhost;
        proxy_cookie_domain stripe.com            localhost;

        location /platform-claude/ {
            set $up_host "platform.claude.com";
            set $up_url  "https://platform.claude.com";
            proxy_pass            $up_url/;
            proxy_ssl_server_name on;
            proxy_ssl_name        $up_host;
            proxy_set_header      Host       $up_host;
            proxy_set_header      Origin     $up_url;
            proxy_set_header      Referer    $up_url/;
            proxy_redirect        $up_url/  /platform-claude/;
        }

        location /openai-platform/ {
            set $up_host "platform.openai.com";
            set $up_url  "https://platform.openai.com";
            proxy_pass            $up_url/;
            proxy_ssl_server_name on;
            proxy_ssl_name        $up_host;
            proxy_set_header      Host       $up_host;
            proxy_set_header      Origin     $up_url;
            proxy_set_header      Referer    $up_url/;
            proxy_redirect        $up_url/  /openai-platform/;
        }

        location /anthropic-console/ {
            set $up_host "console.anthropic.com";
            set $up_url  "https://console.anthropic.com";
            proxy_pass            $up_url/;
            proxy_ssl_server_name on;
            proxy_ssl_name        $up_host;
            proxy_set_header      Host       $up_host;
            proxy_set_header      Origin     $up_url;
            proxy_set_header      Referer    $up_url/;
            proxy_redirect        $up_url/  /anthropic-console/;
        }

        location = /proxy-health {
            access_log off;
            return 200 "proxy-test ok\n";
            add_header Content-Type text/plain;
        }

        access_log @@SERVER_DIR@@/logs/proxy-test-access.log;
        error_log  @@SERVER_DIR@@/logs/proxy-test-error.log warn;
    }

    # ── HTTPS: Live CSS Editor ─────────────────────────────────────────────────
    server {
        listen  127.0.0.1:8443 ssl;
        server_name localhost;

        # mkcert locally-trusted certificate (system keychain CA).
        # Generated by: mkcert -cert-file certs/localhost.pem
        #                       -key-file  certs/localhost-key.pem
        #                       localhost 127.0.0.1 ::1
        ssl_certificate     @@SERVER_DIR@@/certs/localhost.pem;
        ssl_certificate_key @@SERVER_DIR@@/certs/localhost-key.pem;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;

        root  @@PROJECT_DIR@@;
        index index.php index.html;

        charset utf-8;

        error_log  @@SERVER_DIR@@/logs/nginx-error.log warn;
        access_log @@SERVER_DIR@@/logs/nginx-access.log;

        # Block dotfiles except .well-known
        location ~ /\.(?!well-known) {
            deny all;
        }

        # PHP files -- pass to PHP-FPM
        location ~ \.php$ {
            # Reject PHP files that don't exist (avoid running arbitrary uploads)
            try_files $uri =404;

            fastcgi_pass   unix:@@SERVER_DIR@@/run/php-fpm.sock;
            fastcgi_index  index.php;

            # Core FastCGI parameters
            fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
            fastcgi_param  QUERY_STRING      $query_string;
            fastcgi_param  REQUEST_METHOD    $request_method;
            fastcgi_param  CONTENT_TYPE      $content_type;
            fastcgi_param  CONTENT_LENGTH    $content_length;
            fastcgi_param  SCRIPT_NAME       $fastcgi_script_name;
            fastcgi_param  REQUEST_URI       $request_uri;
            fastcgi_param  DOCUMENT_URI      $document_uri;
            fastcgi_param  DOCUMENT_ROOT     $document_root;
            fastcgi_param  SERVER_PROTOCOL   $server_protocol;
            fastcgi_param  GATEWAY_INTERFACE CGI/1.1;
            fastcgi_param  SERVER_SOFTWARE   nginx/$nginx_version;
            fastcgi_param  REMOTE_ADDR       $remote_addr;
            fastcgi_param  REMOTE_PORT       $remote_port;
            fastcgi_param  SERVER_ADDR       $server_addr;
            fastcgi_param  SERVER_PORT       $server_port;
            fastcgi_param  SERVER_NAME       $server_name;
            fastcgi_param  REDIRECT_STATUS   200;

            # Inform PHP it is behind HTTPS so it sets secure cookies correctly.
            fastcgi_param  HTTPS             on;

            # Generous timeouts for AI/image-generation endpoints
            fastcgi_read_timeout    300;
            fastcgi_send_timeout    120;
            fastcgi_connect_timeout  10;

            fastcgi_buffers     16  16k;
            fastcgi_buffer_size     32k;
        }

        # Static files / directory index
        location / {
            try_files $uri $uri/ =404;
        }

        # Block access to sensitive file types
        location ~* \.(env|log|sh|bak|sql|sqlite|db)$ {
            deny all;
        }

        # Long-lived cache for fingerprinted assets
        location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|webp)$ {
            expires 7d;
            add_header Cache-Control "public, immutable";
        }
    }
}
