; php-fpm-pool.conf.tpl -- Live CSS Editor custom PHP-FPM pool
; THIS IS A TEMPLATE.  Do not edit conf/php-fpm-pool.conf directly; it is
; generated by server/setup.sh with machine-specific values substituted.
;
; Placeholders (replaced by setup.sh via sed):
;   @@RUN_USER@@    -- OS user that runs PHP-FPM workers
;   @@RUN_GROUP@@   -- primary group of that user
;   @@PROJECT_DIR@@ -- absolute path to the live-css project root
;   @@SERVER_DIR@@  -- absolute path to the server/ sub-directory

[livecss]
user  = @@RUN_USER@@
group = @@RUN_GROUP@@

; Dedicated unix socket -- isolated from any default "www" pool.
listen = @@SERVER_DIR@@/run/php-fpm.sock
listen.owner = @@RUN_USER@@
listen.group = @@RUN_GROUP@@
listen.mode  = 0660

; Dynamic pool: low idle cost, scales up for AI/image-gen bursts.
pm                   = dynamic
pm.max_children      = 12
pm.start_servers     = 2
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests      = 500

; Working directory
chdir = @@PROJECT_DIR@@

; Logs
php_admin_value[error_log]  = @@SERVER_DIR@@/logs/php-fpm-pool.log
php_admin_flag[log_errors]  = on
slowlog                      = @@SERVER_DIR@@/logs/php-fpm-slow.log
request_slowlog_timeout      = 5s

; PHP ini overrides
php_admin_value[upload_max_filesize]   = 64M
php_admin_value[post_max_size]         = 64M
php_admin_value[max_execution_time]    = 300
php_admin_value[max_input_time]        = 300
php_admin_value[memory_limit]          = 256M
php_admin_value[session.save_path]     = /tmp
php_admin_value[display_errors]        = Off
php_admin_value[log_errors]            = On
