#!/usr/bin/env bash
# setup_keys.sh  -  Interactive API key setup for the Code Review TUI.
# Run from any directory; writes dev-tools/code-review/.keys (gitignored).
#
# Usage:  ./setup_keys.sh

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEYS_FILE="$DIR/.keys"

# ---- Candidate key locations (checked automatically) -----------------------
DESKTOP_OPENAI="$HOME/Desktop/my_keys/openai_key.txt"
DESKTOP_ANTHROPIC="$HOME/Desktop/my_keys/anthropic_key.txt"

# ---- Helpers ----------------------------------------------------------------
read_key_from_file() {
    local file="$1"
    # Grab first non-blank, non-comment line; strip whitespace.
    grep -v '^\s*#' "$file" 2>/dev/null | grep -v '^\s*$' | head -1 | tr -d '[:space:]'
}

print_header() {
    echo ""
    echo "========================================"
    echo "  Code Review TUI  -  API Key Setup"
    echo "========================================"
    echo ""
}

# ---- Load existing values if .keys already exists --------------------------
CURRENT_PROVIDER="openai"
CURRENT_OPENAI=""
CURRENT_ANTHROPIC=""

if [[ -f "$KEYS_FILE" ]]; then
    source "$KEYS_FILE" 2>/dev/null || true
    CURRENT_PROVIDER="${AI_PROVIDER:-openai}"
    CURRENT_OPENAI="${OPENAI_API_KEY:-}"
    CURRENT_ANTHROPIC="${ANTHROPIC_API_KEY:-}"
fi

# ---- Auto-detect desktop key files ------------------------------------------
DETECTED_OPENAI=""
DETECTED_ANTHROPIC=""

if [[ -f "$DESKTOP_OPENAI" ]]; then
    DETECTED_OPENAI="$(read_key_from_file "$DESKTOP_OPENAI")"
fi
if [[ -f "$DESKTOP_ANTHROPIC" ]]; then
    DETECTED_ANTHROPIC="$(read_key_from_file "$DESKTOP_ANTHROPIC")"
fi

# ---- Interactive prompts ----------------------------------------------------
print_header

# -- Provider choice ----------------------------------------------------------
echo "Which AI provider do you want to use?"
echo "  1) OpenAI    (gpt-4o-mini)"
echo "  2) Anthropic (claude-haiku)"
echo ""
if [[ "$CURRENT_PROVIDER" == "anthropic" ]]; then
    DEFAULT_CHOICE=2
else
    DEFAULT_CHOICE=1
fi
read -rp "Choice [${DEFAULT_CHOICE}]: " CHOICE
CHOICE="${CHOICE:-$DEFAULT_CHOICE}"

case "$CHOICE" in
    2) NEW_PROVIDER="anthropic" ;;
    *) NEW_PROVIDER="openai"    ;;
esac
echo "  Provider set to: $NEW_PROVIDER"
echo ""

# -- OpenAI key ---------------------------------------------------------------
if [[ "$NEW_PROVIDER" == "openai" ]]; then
    echo "OpenAI API key:"

    if [[ -n "$DETECTED_OPENAI" ]]; then
        MASKED="${DETECTED_OPENAI:0:8}...${DETECTED_OPENAI: -4}"
        echo "  Detected at $DESKTOP_OPENAI  ($MASKED)"
        read -rp "  Use this key? [Y/n]: " USE_DETECTED
        USE_DETECTED="${USE_DETECTED:-Y}"
        if [[ "$USE_DETECTED" =~ ^[Yy]$ ]]; then
            NEW_OPENAI="$DETECTED_OPENAI"
        else
            read -rp "  Paste OpenAI key: " NEW_OPENAI
        fi
    elif [[ -n "$CURRENT_OPENAI" ]]; then
        MASKED="${CURRENT_OPENAI:0:8}...${CURRENT_OPENAI: -4}"
        echo "  Current key: $MASKED"
        read -rp "  Press Enter to keep, or paste a new key: " NEW_OPENAI
        NEW_OPENAI="${NEW_OPENAI:-$CURRENT_OPENAI}"
    else
        read -rp "  Paste OpenAI key (or leave blank to skip): " NEW_OPENAI
    fi
    NEW_ANTHROPIC="${CURRENT_ANTHROPIC:-}"
fi

# -- Anthropic key ------------------------------------------------------------
if [[ "$NEW_PROVIDER" == "anthropic" ]]; then
    echo "Anthropic API key:"

    if [[ -n "$DETECTED_ANTHROPIC" ]]; then
        MASKED="${DETECTED_ANTHROPIC:0:6}...${DETECTED_ANTHROPIC: -4}"
        echo "  Detected at $DESKTOP_ANTHROPIC  ($MASKED)"
        read -rp "  Use this key? [Y/n]: " USE_DETECTED
        USE_DETECTED="${USE_DETECTED:-Y}"
        if [[ "$USE_DETECTED" =~ ^[Yy]$ ]]; then
            NEW_ANTHROPIC="$DETECTED_ANTHROPIC"
        else
            read -rp "  Paste Anthropic key: " NEW_ANTHROPIC
        fi
    elif [[ -n "$CURRENT_ANTHROPIC" ]]; then
        MASKED="${CURRENT_ANTHROPIC:0:6}...${CURRENT_ANTHROPIC: -4}"
        echo "  Current key: $MASKED"
        read -rp "  Press Enter to keep, or paste a new key: " NEW_ANTHROPIC
        NEW_ANTHROPIC="${NEW_ANTHROPIC:-$CURRENT_ANTHROPIC}"
    else
        read -rp "  Paste Anthropic key (or leave blank to skip): " NEW_ANTHROPIC
    fi
    NEW_OPENAI="${CURRENT_OPENAI:-}"
fi

# ---- Write .keys ------------------------------------------------------------
cat > "$KEYS_FILE" <<EOF
# dev-tools/code-review/.keys
# Gitignored — do NOT commit this file.
# Generated by setup_keys.sh on $(date "+%Y-%m-%d %H:%M")

AI_PROVIDER=${NEW_PROVIDER}

OPENAI_API_KEY=${NEW_OPENAI}
ANTHROPIC_API_KEY=${NEW_ANTHROPIC}
EOF

chmod 600 "$KEYS_FILE"

echo ""
echo "Saved to: $KEYS_FILE"
echo ""
echo "Provider : $NEW_PROVIDER"
if [[ -n "$NEW_OPENAI" ]];    then echo "OpenAI   : ${NEW_OPENAI:0:8}...${NEW_OPENAI: -4}"; fi
if [[ -n "$NEW_ANTHROPIC" ]]; then echo "Anthropic: ${NEW_ANTHROPIC:0:6}...${NEW_ANTHROPIC: -4}"; fi
echo ""
echo "Run ./run.sh to launch the editor with these keys active."
echo ""
