#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const readme = [
"# Crissy's Style Tool",
"",
"A desktop CSS/HTML/JavaScript live editor with real-time preview and an integrated AI agent, built with Tauri v2 and PHP.",
"",
"**Author:** Crissy Deutsch  ",
"**Company:** XcaliburMoon Web Development  ",
"**Website:** https://xcaliburmoon.net/  ",
"**License:** MIT",
"",
"---",
"",
"## Overview",
"",
"Crissy's Style Tool is a floating-panel code editor designed for rapid CSS prototyping and front-end development. Three resizable CodeMirror editors (CSS, HTML, JS) sit alongside a live preview iframe. All panels are freely draggable, minimizable, and restore their positions between sessions.",
"",
"An AI Agent window is built into the app. It connects to Anthropic, OpenAI, or DeepSeek and can generate HTML/CSS from scratch, apply targeted changes to the current editor content, or have an open-ended chat. Generated code can be reviewed in a diff view and applied directly to the editors with one click.",
"",
"---",
"",
"## Features",
"",
"### Editors",
"- Three independent CodeMirror 5 editors: CSS, HTML, JavaScript",
"- Syntax highlighting and linting (CSSLint, JSHint, HTMLHint)",
"- Code folding with fold gutter",
"- Per-panel inline search with match count and orange highlights",
"- Undo/redo buttons in each panel header",
"- Custom indent guides with color, opacity, thickness, style, and step settings",
"- Column ruler with configurable position and color",
"- Autosave every 1.5 seconds to localStorage",
"",
"### Fuzzy Autocomplete",
"- Context-aware CSS completions: property names before `:`, value keywords after `:`",
"- JavaScript and HTML completions",
"- Dropdown flips above cursor when near the bottom of the editor",
"- Arrow key navigation with scroll-into-view",
"- Capture-phase keyboard interception so arrow keys never move the editor cursor while the dropdown is open",
"",
"### Inline Widgets",
"- Color swatch diamonds next to every color value -- click to open a color picker",
"- Size slider diamonds next to every numeric measurement -- drag to adjust values live",
"- Supports all CSS units: px, em, rem, %, vh, vw, vmin, vmax, pt, pc, ch, ex, cm, mm, in, fr, s, ms, deg, turn",
"- Bare numbers (flex: 1, gap: 0) are also detected",
"",
"### Color Harmony Tool",
"- Floating panel with seven harmony modes: Complementary, Analogous, Triadic, Split-Comp, Tetradic, Square, Monochromatic",
"- Base color picker with hex readout",
"- Click any swatch to insert it into the active editor",
"",
"### Wireframe Tool",
"- Full-canvas layout prototyping tool (1200x900 canvas)",
"- Add, move, and resize rectangles with mouse drag or arrow keys (1px; Shift+arrow for 10px)",
"- Adjust per-element label, position, size, margin, padding, background color, border color, border width, and border radius",
"- Nest elements inside each other via Parent selector",
"- Anti-overlap enforcement: siblings cannot touch or overlap (including margin areas)",
"- Children are constrained inside parent padding",
"- Horizontal and vertical ruler strips with tick marks every 25px, labels every 100px",
"- Drag from a ruler strip to create guide lines; drag guides to reposition; double-click to delete",
"- Save wireframe as JSON, load from JSON, and Copy Context (CSS comment block for AI or documentation use)",
"- Auto-saves to localStorage on every change",
"",
"### Session Management",
"- Save/load named projects to localStorage",
"- Session history restore bar on startup (last 10 sessions)",
"- Manual save and load modals",
"- Reset Layout button restores default panel positions",
"",
"---",
"",
"## AI Agent",
"",
"The Agent is a floating, resizable window (860x580px) that launches from the header toolbar. It persists its settings (provider, model, task, source, active tab) to localStorage between sessions.",
"",
"### Tasks",
"- **Build Something New** -- describe a component or layout; the agent picks the best CSS theme and generates complete, correct HTML",
"- **Request a Change** -- send the current editor content as context and describe modifications; the agent returns a targeted diff",
"- **Chat** -- open-ended conversation with the selected AI provider",
"",
"### Source Modes",
"- **Crissy's Editors** -- uses the live CSS and HTML content from the three CodeMirror editors as context",
"- **Load a File** -- paste or load an external file as the source context",
"",
"### Apply Bar",
"- After a generation finishes, a diff view shows the before/after",
"- Apply to Editors patches the CSS and HTML editors in place with no copy/paste required",
"",
"### Neural Animation",
"- While the agent is working, a canvas overlay shows a drifting neural network with animated signal pulses",
"- Conversational phrases are displayed over the animation; the phrase pool is seeded from GPT-4o-mini on first use and stored in a local SQLite database (ai/data/phrases.db)",
"",
"### Providers",
"",
"| Provider | Endpoint | Default Model |",
"|----------|----------|---------------|",
"| Anthropic | ai/anthropic.php | claude-opus-4-5 |",
"| OpenAI | ai/openai.php | gpt-4o |",
"| DeepSeek | ai/deepseek.php | deepseek-chat |",
"",
"Provider API keys are stored in ai/config.json (not committed to version control).",
"",
"---",
"",
"## CSS Theme System",
"",
"The style-sheets/ folder contains seven production-ready CSS design systems. The agent uses the theme system to pick the right one for any request and to resolve correct class names, prefixes, and variables.",
"",
"### Themes",
"",
"| Key | Prefix | File | Description |",
"|-----|--------|------|-------------|",
"| atom-age | aa | atom-age.css | Retro space-age, warm amber tones |",
"| clean-system | -- | clean-system.css | Minimal system UI for dev tools |",
"| crystal-ui | cr | crystal-ui.css | Glassmorphism with translucent surfaces |",
"| dark-neu | dn | dark-neu.css | Dark neumorphism |",
"| keyboard-ui | kb | keyboard-ui.css | Keyboard/terminal aesthetic |",
"| neon-grid | ng | neon-grid.css | Cyberpunk neon on dark grid |",
"| neumorphism | neu | neumorphism.css | Classic soft neumorphism |",
"",
"### Theme Data Structure",
"",
"Theme metadata is split across two locations for fast lookup:",
"",
"- style-sheets/theme_handler.json -- lightweight routing manifest containing scoring data (description, best_for, avoid_for, visual_identity, components_available, palette_keywords, component_coverage) for all seven themes",
"- style-sheets/themes/{key}.json -- heavy per-theme detail (palette, variables, line counts) loaded on demand only for the winning theme",
"",
"style-sheets/parser.php reads theme_handler.json at startup and lazy-loads the per-theme file only when building the full AI context object. style-sheets/fuzzy-search.php searches against theme_handler.json for fast component and keyword lookups.",
"",
"---",
"",
"## Technology Stack",
"",
"| Layer | Technology |",
"|-------|-----------|",
"| Desktop shell | Tauri v2 (Rust) |",
"| Backend | PHP 8.x built-in server |",
"| Editors | CodeMirror 5.65.16 (local vendor) |",
"| Linters | CSSLint 1.0.5, JSHint 2.13.6, HTMLHint 0.16.3 |",
"| AI streaming | Server-Sent Events via PHP, consumed by the agent JS modules |",
"| Phrase storage | SQLite via PHP (ai/data/phrases.db) |",
"| JS modules | Vanilla ES5/ES6, namespaced under window.LiveCSS |",
"| CSS | Custom dark theme, no framework |",
"",
"---",
"",
"## Project Structure",
"",
"```",
"live-css/",
"  index.php                    Main HTML shell and PHP data bridge",
"  style.css                    Global styles",
"  css/                         Modular CSS files",
"    base.css",
"    layout.css                 Panel layout",
"    agent.css                  AI agent floating window",
"    ai-chat.css                Chat tab styles",
"    fuzzy.css                  Autocomplete dropdown",
"    wireframe.css              Wireframe tool",
"    color-tools.css",
"    ...",
"  js/                          Modular JavaScript files",
"    app.js                     Boot and wiring",
"    agent.js                   Agent entry point (loads agent/ modules)",
"    agent/                     AI agent modules",
"      agent-core.js            State, settings persistence, busy/idle",
"      agent-ui.js              DOM rendering and panel construction",
"      agent-run.js             SSE streaming runner (run.php mode)",
"      agent-diff.js            Diff view and apply-to-editors",
"      agent-context.js         Context building from editors",
"      agent-prompts.js         Prompt assembly",
"      agent-chat.js            Chat tab logic",
"      agent-window.js          Floating window drag, resize, minimize",
"      agent-neural.js          Neural network canvas animation + phrases",
"    editor.js                  CodeMirror setup and live preview",
"    fuzzy.js                   Fuzzy autocomplete",
"    color-swatch.js            Inline color swatch diamonds",
"    size-slider.js             Inline size slider diamonds",
"    color-harmony.js           Color harmony tool",
"    wireframe.js               Wireframe / layout prototyping tool",
"    gutter.js                  Resizable/draggable panel system",
"    editor-search.js           Per-panel inline search",
"    indent-guide.js            Custom indent guides",
"    storage.js                 localStorage persistence",
"    modal-save.js",
"    modal-load.js",
"    property-lookup.js         CSS properties reference",
"    native-bridge.js           Tauri native file/bridge integration",
"    cdn-loader.js              Local-first CodeMirror loader with CDN fallback",
"    utils.js                   Shared utilities",
"  ai/                          PHP AI backend",
"    config.json                API keys (not committed)",
"    config.php                 Key loader",
"    anthropic.php              Anthropic SSE endpoint",
"    openai.php                 OpenAI SSE endpoint",
"    deepseek.php               DeepSeek SSE endpoint",
"    phrases.php                Phrase pool (SQLite + GPT-4o-mini seed)",
"    data/",
"      phrases.db               SQLite database for agent phrases",
"    agent/",
"      agent.php                Agent action router",
"      run.php                  Full agent run with parser context",
"      diff.php                 Diff utilities",
"      outline.php              CSS outline extractor",
"      db.php                   Database helpers",
"      prompts.json             Agent and mode prompt templates",
"      context/",
"        context.php            Context assembler",
"  style-sheets/                CSS theme system",
"    theme_handler.json         Routing manifest for all 7 themes",
"    themes/                    Per-theme detail files (lazy-loaded)",
"      atom-age.json",
"      clean-system.json",
"      crystal-ui.json",
"      dark-neu.json",
"      keyboard-ui.json",
"      neon-grid.json",
"      neumorphism.json",
"    parser.php                 Theme router and AI context builder",
"    fuzzy-search.php           Cross-source fuzzy search",
"    rules.json                 Component and naming rules",
"    atom-age.css",
"    clean-system.css",
"    crystal-ui.css",
"    dark-neu.css",
"    keyboard-ui.css",
"    neon-grid.css",
"    neumorphism.css",
"  data/",
"    css-properties.php         CSS property reference data",
"    property-values.php        CSS property value keyword map",
"    default-content.php        Default editor content",
"  vendor/",
"    codemirror/                CodeMirror 5.65.16 (local copy)",
"    linters/                   CSSLint, JSHint, HTMLHint",
"  src-tauri/                   Tauri Rust application",
"  scripts/                     Build and deploy scripts",
"    copy-www.js                Copies web assets to src-tauri/www",
"    split-learn-json.js        Splits theme metadata into per-theme files",
"    gen-icon.js                App icon generator",
"```",
"",
"---",
"",
"## Running Locally (PHP server)",
"",
"```bash",
"php -S 127.0.0.1:7777 -t src-tauri/www",
"```",
"",
"Then open http://127.0.0.1:7777 in a browser.",
"",
"---",
"",
"## Building the Desktop App",
"",
"```bash",
"node scripts/copy-www.js",
"npm run tauri build",
"```",
"",
"Requires Rust, Cargo, and the Tauri CLI. copy-www.js must be run before each build to sync the web assets into src-tauri/www/.",
"",
"For live development:",
"",
"```bash",
"npx tauri dev",
"```",
"",
"---",
"",
"## License",
"",
"MIT License -- see [LICENSE](LICENSE) for full text.",
"",
"Copyright (c) 2026 Crissy Deutsch / XcaliburMoon Web Development  ",
"https://xcaliburmoon.net/",
""
].join("\n");

const out = path.resolve(__dirname, '..', 'README.md');
fs.writeFileSync(out, readme, 'utf8');
console.log('wrote', out, readme.split('\n').length, 'lines');
